<?
$PERM["admin"]["14"]="R";
$PERM["admin"]["10"]="R";
$PERM["admin"]["12"]="R";
$PERM["admin"]["11"]="R";
$PERM["admin"]["*"]="D";
$PERM["tools"]["5"]="T_8";
$PERM["rk.php"]["5"]="T_8";
$PERM["wizards"]["*"]="D";
?>